name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --tag ghcr.io/domvo/docker-deploy:latest
    - run: echo ${{ secrets.PAT }} | docker login ghcr.io -u domvo --password-stdin
    - run: docker push ghcr.io/domvo/docker-deploy:latest
