name: Preview App on PR

on:
  pull_request:
  workflow_dispatch:

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        SLUGG=$(echo ${{ github.ref_name }} | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z) 
        echo "SLUG=$SLUGG" >> $GITHUB_ENV
    - run: docker build . --tag ghcr.io/domvo/astrosite:$SLUG
    - run: echo ${{ secrets.PAT }} | docker login ghcr.io -u domvo --password-stdin
    - run: |
        docker push ghcr.io/domvo/astrosite:$SLUG

  run-docker-container:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
    - run: |
        SLUGG=$(echo ${{ github.ref_name }} | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z) 
        echo "SLUG=$SLUGG" >> $GITHUB_ENV
    - uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
      with:
        host: 165.227.157.221
        username: dome
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u domvo --password-stdin
          docker pull ghcr.io/domvo/astrosite:$SLUG
          docker stop $SLUG
          docker system prune -f
          docker run -d --name=pullreq --network=traefik --label traefik.enable=true --label traefik.http.routers.$SLUG.rule=Host\(\`$SLUG.dokku.devsters.de\`\) --label traefik.http.routers.$SLUG.entrypoints=web ghcr.io/domvo/astrosite:$SLUG
